// Code generated by "stringer -type=RouteType"; DO NOT EDIT

package ptv

import "fmt"

const _RouteType_name = "TrainTramBusVLineNightBus"

var _RouteType_index = [...]uint8{0, 5, 9, 12, 17, 25}

func (i RouteType) String() string {
	if i < 0 || i >= RouteType(len(_RouteType_index)-1) {
		return fmt.Sprintf("RouteType(%d)", i)
	}
	return _RouteType_name[_RouteType_index[i]:_RouteType_index[i+1]]
}
